services:
  app:
    image: henrygd/beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=45876
      - KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    app_data: